"""empty message

Revision ID: 6eea3a6efbe0
Revises: 77d34de14fdc
Create Date: 2022-12-16 23:59:57.650705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6eea3a6efbe0'
down_revision = '77d34de14fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_term',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.String(length=32), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('title_holder_player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('title_holder_player_id')
        batch_op.drop_column('term')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title_holder_player_id', mysql.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('tournament_term')
    # ### end Alembic commands ###
