"""empty message

Revision ID: 77d34de14fdc
Revises: b808b2ec6cb0
Create Date: 2022-12-13 00:16:08.428072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d34de14fdc'
down_revision = 'b808b2ec6cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'news_provider', ['news_provider_id'], ['id'])

    with op.batch_alter_table('news_tag', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'news', ['news_id'], ['id'])

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'player', ['master_id'], ['id'])
        batch_op.create_foreign_key(None, 'player_grade', ['grade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('news_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
