"""empty message

Revision ID: a65ff7ba0ce4
Revises: 6eea3a6efbe0
Create Date: 2022-12-17 00:37:04.977137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65ff7ba0ce4'
down_revision = '6eea3a6efbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_official', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('is_official')

    # ### end Alembic commands ###
