"""empty message

Revision ID: fb6e81a424b3
Revises: d5a3ff7db47e
Create Date: 2022-12-23 00:12:01.872781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb6e81a424b3'
down_revision = 'd5a3ff7db47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_news_tag',
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('news_tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['news_tag_id'], ['news_tag.id'], )
    )
    with op.batch_alter_table('news_tag', schema=None) as batch_op:
        batch_op.drop_constraint('news_tag_ibfk_1', type_='foreignkey')
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('news_tag_ibfk_1', 'news', ['news_id'], ['id'])

    op.drop_table('news_news_tag')
    # ### end Alembic commands ###
