version: "3"
services:
  api:
    build: .
    ports:
      - "15000:5000"
    container_name: shogi-lake-api
    volumes:
      - ./app:/app
    environment:
      ENV: local
      FLASK_APP: api/main
    command: flask run --host=0.0.0.0

  db:
    image: mysql:latest
    platform: linux/x86_64
    container_name: shogi-lake-db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shogi_lake
      MYSQL_USER: shogi_lake_user
      MYSQL_PASSWORD: shogi_lake_password
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - "33066:3306"
    networks:
      - shogi_lake_nw

networks:
  shogi_lake_nw:

